name: Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '12'
        - name: Install packages
          run: npm i
        - name: Set Creds
          run: git config user.name "mug1wara26" && git config user.email "aloysiusgsq@gmail.com"
        - name: Deploy
          run: npm run deploy

  backend-google-cloud-deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: backend
          FOLDER: cs6131-backend
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
